language: ruby
cache: bundler
rvm:
- 2.2.4

env:
  global:
    secure: uL/BvJj4OaAb6mErntqc7ogDtEHAAab6Zp6sNoP5if1KZ9pxCP8XW17OjQJjuela21gx3HoSbp/cBSORxGZM3HbvyYNYVc6hUc+uAC6l0kK4mbdXhwAq+uX3Eh/M5IeP6oV3bCrSSo03cGzBpdTvscOaTk3kdR/2Grk02PB7hTqsIP7vdlksiyzoBPFhdiM/ks9Uf3zIlLpT/YwY0/zneewwUnEQnZsPLBxWaULqlpjc3pMQG2ljS9LZTUxZ6zd5aiOwOcWqDrPtLgu5wF/5FgnFPwmjLZl/SYxrgpwjTsbYAuagD1DrOiY6a9+JHwin+MeL66OYhHygsYJ7Wz8sux1vvtfyIxpUp8E7qKdsqaY8JPfy6o5ChE0wA+CqW6MF8/K7/lRvuza+4g+VNyfgLzKD4sXZwP3V/t8OBs8yREWtMcJWwsUrTo0tbtXbrY/I0tMXOUnk0NrajE3w4qF1gyfdT5yW624afKRGO3dY+MXHzXjB/ZYnEeyY9eiBeFucgLeWD6PW+zoVZzIoOdA3BDnrRDP28rud/mx5TvJTXatixZi3lqM0YGSf3pini2lHE3CESSO2/5/MpD6fRtzJOeIPy/BsBSb09dRvAYDRKkP9Udrn+PqL4hZgymz/rjs/LjdvkDBpn1yRXFBqH6tgFHBt9PwlI1Te7vPoMNa2tKU=

before_install:
- openssl aes-256-cbc -K $encrypted_411b6a7e5ad0_key -iv $encrypted_411b6a7e5ad0_iv -in spec/fixtures/drive_key.json.enc -out drive_key.json -d

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"

# test and build
script:
- bundle exec rspec

# deploy gem
deploy:
  provider: rubygems
  api_key:
    secure: Bz3m+YToIhPrtbkPrRa12ePf+hWtHdflzqRnaq+aYrpZgiCQ6TQPbCJwX7sreTwBvIcFqxMy8kW8MWmM0AxbrYAgAZY9aWhsplLnQe2ojHaRUL+EdbdxR/rsAA6DEEMjUpv91Ts3ef/Z4q/c3aNuCkp9A+G9y/gZu4P6a0rBxLqi7oL53cFQNJKd7qH7+KtIomxTpc+IZ8lEnYDkSsD65sTL/zWpCqzTt9qKr6zgT1m5P6pDp3jrhWA4CByWdjWMtIdIy+5WaObv0NkTJb1ocPgEdGEJCEqtzs92LWR8WTXIwlxWi3HBH0ZkS+SgQzrp1bXXtyCTddOgJgpSpcwUNG/qdCE8kdmqlvENwNe7BIWUbax16dksKg0aLXPiLEji8F/pOI1d59q2AKM+aevV0hqUOJIgKpGxqRjFLZpZktFNZY/hYw7XAcSRwNrF4A6EcSBkaizwsmq91WvDjKr3TL04wgkV4M2UYLesf8qHmuS75l1ooiT1Fz2x4NOff/XKeY8CNd5yFBk0ufc4P0vmvs2hFDSG/alFBKjp893WMOM1t7Dd4+7cre4frw+aBkSJF6oZbD40Tdd3fGENYICyaOB4Rz4VDFheZkRVEG0ff5FDXP1PQGFs2dDc3UbXlBEKqmhvc7hNNtEuPn3nnyghxNam5A3DUMYsX/10NwHLyxE=
  gem: fastlane-plugin-google_drive
  on:
    branch: master
    tags: true
    repo: bskim45/fastlane-plugin-google_drive
  skip_cleanup: true

# send the coverage data to Code Climate
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
